version: '3.9'

services:
  nginx:
    image: nginx:1.25.2-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"
    networks:
      - rinha-net

  api1:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: api1
    hostname: api1
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOSTNAME=db
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "100MB"
    networks:
      - rinha-net
      - payment-processor

  api2:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: api2
    hostname: api2
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOSTNAME=db
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "100MB"
    networks:
      - rinha-net
      - payment-processor

  db:
    image: postgres:16.0-alpine
    container_name: db
    hostname: db
    environment:
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_DB=rinha
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rinha -d rinha"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rinha-net

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true
